### ISSUE TITLE
geoapi-proj4/src/main/native/jniproj.c doing angular conversions for geocentric case

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geoapi#26]
convertAngularOrdinates() in geoapi-proj4/src/main/native/jniproj.c does radians <--> degrees conversion for a geocentric PJ* object, which looks inappropriate as coordinates are in linear units

**Comment by desruisseaux** [comment]
Indeed, this is a bug. Thanks for spotting that.

This issue can be related to https://github.com/OSGeo/proj.4/issues/903
