### ISSUE TITLE
In Metadata, associate java.util.Locale with Charset

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/geoapi#28]
Figure 23 of ISO 19115:2014 defines `PT_Locale` as a type having the following properties:

* `language` : `languageCode`
* `country` : `CountryCode` [0 … 1]
* `characterEncoding` : `MD_CharacterSetCode`

In Java, the language and the country are represented by `java.util.Locale` while the character encoding is represented by `java.nio.charset.Charset`. We wish to avoid creating a new type duplicating the standard java types. So GeoAPI `Metadata` interface is currently proposing the following methods (not yet released):

* `Metadata.getLanguages()` returns a collection of `Locale`
* `Metadata.getCharacterSets()` returns a collection of `Charset`

The problem is that above methods does not allow to know which `Charset` is used with which `Locale`. A possible approach is to replace above methods by:

* `Metadata.getLanguages()` returns a `Map<Locale, Charset>`.

Note that `Locale` is final in Java SE, so its use in a `Map` is safe.

**Comment by kinow** [comment]
Haven't seen the specification, but I think `getLanguages` and `getCharacterSets` sounds OK. I'd be fine with `getCharsets` too.

>The problem is that above methods does not allow to know which Charset is used with which Locale.

Normally in Portuguese we use `IS-8859-1`, but `UTF-8` is used as well. Wouldn't it work best to leave both methods unrelated. I think it's common that other languages that normally use a different charset may use `UTF-8` too.

**Comment by desruisseaux** [comment]
In ISO 19115-1:2014, the language, country and character encoding are bundled together in the same `PT_Locale` object. This is the problem we are facing because in Java, `Locale` and `Charset` are separated objects (and I agree about the advantages of keeping them separated). Our problem is: how to carry the information that this specific `Charset` was aimed to be used with that particular `Locale`? I agree that in a pure Java world, we do not really need such association. But when marshalling a metadata to an ISO 19115-3 compliant XML document, we need that information in order to reconstitute the `PT_Locale` instances expected by the standard. This ambiguity is the current blocker of [SIS-402](https://issues.apache.org/jira/browse/SIS-402) issue.

Our current choices (as I see them) are:

1. Leave the situation as-is (`Collection<Locale>` and `Collection<Charset>` provided separately) and let implementations resolve the ambiguity as they want at XML marshalling time.
2. Introduce a new `PT_Locale` class in GeoAPI which contains two properties ─  `Locale` and `Charset` ─ and replace existing two properties by a single `Collection<PT_Locale>`.
3. Replace the existing two properties by a single `Map<Locale, Charset>`, which provides some of the benefit of choice 2 without introducing a new class.

**Comment by desruisseaux** [comment]
Replaced previous methods by:

```
@UML(identifier="defaultLocale+otherLocale", obligation=CONDITIONAL, specification=ISO_19115)
Map<Locale,Charset> getLocalesAndCharsets();
```

May be revisited if there is feedback on this proposal.
