### ISSUE TITLE
Any interest in moving the site to GitHub pages?

### ISSUE THREAD

**Issue by kinow** [opengeospatial/geoapi#33]
Hi, recently there was a short outage in the web server. The domain name was OK, so I assume it was something in nginx/httpd.

Is there interest in moving the homepage to GitHub pages or to an alternative hosting solution? If so I'd be happy to help.

That way I can also review the docs and learn a bit more.

B

**Comment by desruisseaux** [comment]
Hello Bruno. Thanks for your offer. I'm not familiar with GitHub hosting. Would it allow to keep the http://www.geoapi.org domain name?

Alternatively, another proposal was to transfer www.geoapi.org domain ownership to OGC since GeoAPI is an OGC working group. I don't know if OGC staff would be willing to take it?

**Comment by kinow** [comment]
>Would it allow to keep the http://www.geoapi.org domain name?

[Yup](https://help.github.com/articles/using-a-custom-domain-with-github-pages/). You just need to update the DNS registrar, and tell it to forward requests to GitHub DNS servers, and then add a CNAME file like this one https://github.com/kinow/kinoshita.eti.br/blob/master/CNAME.

I maintain my own blog, but also biouno.org, and Apache OpenNLP is using Apache gitpubsub, which allowed hosting the site in GitHub too. The source code is Java, which is a bit unusual, but it gets rendered to static HTML via JBake. The source code is hosted at https://github.com/apache/opennlp-site, and the static content is served from the asf-site branch https://github.com/apache/opennlp-site/tree/asf-site.

The main advantage, in my opinion, is that users can fork the repository, fix/edit/work on their fork, preview the site in their fork, all without the need to install anything locally (unless they want or need to run the site locally, of course) and then send pull requests.

>Alternatively, another proposal was to transfer www.geoapi.org domain ownership to OGC since GeoAPI is an OGC working group. I don't know if OGC staff would be willing to take it?

I think transferring ownership to OGC - if they were willing to receive it and have resources to maintain it - would be grand. Not involved with OGC right now, but I have a friend that has been the technical representative for our company in OGC for a while. I can ask him if he knows how it works, if necessary? Or we can just drop them a message I think...

**Comment by kinow** [comment]
Oh, and a few days ago GitHub announced the LetsEncrypt integration for custom domains. So we could also use HTTPS for geoapi.org for free, which might increase the SEO hits in Google/Yahoo/Bing/etc.

**Comment by desruisseaux** [comment]
Just for allowing me to understand: if the site is only static pages (created by `mvn site` + `javadoc` + `asciidoc` + `sphinx`), how do we put them on a GitHub hosting? Do we copy the files using `scp`, or do we commit the files to some Git repository?

**Comment by kinow** [comment]
>if the site is only static pages (created by mvn site + javadoc + asciidoc + sphinx),

Right

>how do we put them on a GitHub hosting? Do we copy the files using scp, or do we commit the files to some Git repository?

Basically, one branch is from where the site is served (like a virtual host in a web server). If you have source code in the `master` branch, you will probably create another branch like `site`, or `gh-pages` to serve the static content from.

Or you can have a folder like `/docs` from which the static site is served. It works well in some projects where the documentation is included with the main sources. Though pull requests can get out of control that way too.

If you create a new repository just for the site, say, github.com/opengeospatial/geoapi-site. Then first GitHub follows the convention to have the site URL, which is using the `github.io` domain. So the site would be `opengeospatial.github.io/geoapi-site`. Assuming, of course, you enabled GitHub pages and there were no errors.

If you repository contains a CNAME file, however, GitHub will also redirect any requests their DNS servers receive for that domain, to this GitHub pages. So if you changed in the registrar for geoapi.org to point to the GitHub DNS servers, and the opengeospatial/geoapi-site contained a CNAME file with the content like `geoapi.org`, then the site would be served, from whichever branch you configured to be the static content "virtual host".

Hope it makes sense. You can also check the [GitHub pages docs](https://pages.github.com/) and try first on a repository in your user account. Once enabled GitHub pages, you should be able to play with a URL like desruisseaux.github.io/<repository-name>. All for free, with low latency normally, and very little downtime (I haven't experienced any, except for a minor glitch during some DDOS I think).

**Comment by desruisseaux** [comment]
Hello @gbuehler; is there an interest from OGC to take ownership of http://www.geoapi.org domain name? And to host the site on an OGC server (or alternatively to use a GitHub service)? The reason for this question is that the current web server sometime have outage.

**Comment by desruisseaux** [comment]
On a related topic, I wonder if we should replace the Maven site by another framework for producing the web site. Does GitHub (or other host facility) provides some framework for that? Something more advanced than wiki pages.

**Comment by kinow** [comment]
That sounds like a good idea @desruisseaux . There are several flavours, [Jekyll](https://jekyllrb.com/) being the more GitHub-friendly. I'm using [Piecrust](https://bolt80.com/piecrust/en/latest/getting-started/) for my site, Jekyll for some Open Source projects, Apache OpenNLP uses [JBake](https://jbake.org/), and another famous framework is [Pelican](https://blog.getpelican.com/).

Main advantage of Jekyll are the GitHub integration, variety of themes, and amount of SO answers, documentation, tutorial, examples, etc.

**Comment by desruisseaux** [comment]
I'm experimenting (using a [separated project](https://github.com/unitsofmeasurement/seshat/issues/12)) the creation of a web site hosted on GitHub. My current understanding is:

* Since GeoAPI is a https://github.com/opengeospatial/ project, the repository for web pages would be `opengeospatial.github.io`. But that repository would be for the whole OGC organisation, we can not use it for GeoAPI only.
* Our only possibility is [to create a `gh-pages` branch](https://help.github.com/en/articles/creating-project-pages-using-the-command-line) in the GeoAPI project. It would result in pages being published at the http://opengeospatial.github.io/geoapi/ URL.
* We can redirect http://www.geoapi.org to http://opengeospatial.github.io/ but I found no way (by reading the [documentation](https://help.github.com/en/articles/using-a-custom-domain-with-github-pages) only) to redirect to a `geoapi` sub-folder.

Is the above correct?

**Comment by kinow** [comment]
Instead of gh-pages, you could also have another repository exclusively for the site. But I think the gh-pages is simpler. So the above looks correct to me 👏

**Comment by desruisseaux** [comment]
Re-created the web site and pushed [as a `gh-pages` branch](https://github.com/opengeospatial/geoapi/tree/gh-pages). The result can be viewed on http://www.geoapi.org which is back online, now served by GitHub.

I must admit that I'm surprised that it worked. I was afraid that we would have to abandon the www.geoapi.org domain name, or that we would be forced to append a directory (e.g. "www.geoapi.org/geoapi"), or that we would be forced to use some GitHub-specific markup language. Many thanks to @kinow for guiding!

**Comment by kinow** [comment]
I didn't do anything, you did the whole hard work.

Tested www.geoapi.org and it worked fine! And quite quick (I believe GitHub pages has some good servers or maybe a CDN?).

Couple things for improvement I think. Will create issues for these.

- www.geoapi.org is working, but not geoapi.org. That can be fixed in the DNS server.
- https://www.geoapi.org is not working. Sites with SSL enabled are preferred over non-SSL (both by SEO engines, and by browsers nowadays). There are ways to have free SSL with GitHub pages
