### ISSUE TITLE
license used here / SPDX License List

### ISSUE THREAD

**Issue by jlovejoy** [opengeospatial/geoapi#45]
hi, could someone from Open Geospatial possibly comment on this https://github.com/spdx/license-list-XML/issues/845

Thanks!
Jilayne
SPDX legal team co-lead

**Comment by desruisseaux** [comment]
Hello. GeoAPI is licensed under the terms of [OGC software license](http://www.opengeospatial.org/ogc/software), which is BSD-like. It is slightly different than the [OGC document license](http://www.opengeospatial.org/ogc/document) that OGC use for the standards they publish. There is a [FAQ here](http://www.opengeospatial.org/ogc/legalfaq).

Is the above answering your question? I can contact OGC board if further clarification is desired.

**Comment by jlovejoy** [comment]
more discussion on that thread, so I'll close this one, now that I got your attention ;)

Thanks!!
