### ISSUE TITLE
Transfer "www.geoapi.org" domain to OGC

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/geoapi#51]
The "www.geoapi.org" domain name is currently owned by Geomatys, which was also hosting the http://www.geoapi.org web site. Following a hardware failure, the GeoAPI web site has been off-line for 3 weeks (issue #49), which prompted the move to GitHub as a hosting service (issue #33). Consequently, as of today there is no remaining piece of GeoAPI on Geomatys side except the domain name; everything else is on GitHub.

@ogcscotts , @gbuehler , does OGC has an interest in taking the ownership of www.geoapi.org domain name? There is no technical work required (no server to provide), only keep the `www.geoapi.org` domain pointing to `opengeospatial.github.io` until OGC decides otherwise.

**Comment by ogcscotts** [comment]
@desruisseaux Yes, OGC will be happy to take on the domain. I will enter a ticket for our infrastructure team to work with you on the transition.

**Comment by kstegemoller** [comment]
@desruisseaux I will start the domain transfer.  I will contact you via your Geomatys email.

**Comment by desruisseaux** [comment]
Hello @kstegemoller. Can you confirm that the transfer is completed?

**Comment by kstegemoller** [comment]
@desruisseaux The transfer is complete and the DNS is pointed to GitHub pages.  You may close this.

**Comment by desruisseaux** [comment]
Thanks for the confirmation. Closing this task.
