### ISSUE TITLE
Configure DNS to allow geoapi.org

### ISSUE THREAD

**Issue by kinow** [opengeospatial/geoapi#53]
Currently, only www.geoapi.org is working. Could we enable geoapi.org as well? It is common practice to support both, as some users may find it easier to type the shorter form.

I don't remember the last time I did that, but I think these articles may be of help.

- https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/
- https://www.freecodecamp.org/news/why-cant-a-domain-s-root-be-a-cname-8cbab38e5f5c/

From what I remember, my A domain entry would be something like geoapi.org, and then I would have a CNAME (alias) www.geoapi.org.

**Comment by kinow** [comment]
New DNS server correctly configured! Now both w/ and w/o www work!!! :tada:

**Comment by desruisseaux** [comment]
Thanks for the confirmation! I didn't verified before.
