### ISSUE TITLE
Change GeoAPI license to Apache 2?

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/geoapi#81]
The [OGC license page](https://www.ogc.org/ogc/software) now (as of January 2023) lists two licenses:

* [Apache Software License 2.0](https://www.ogc.org/ogc/software/2.0). This license became active January 2004.
* [OGC software license 1.0](https://www.ogc.org/ogc/software/1.0). This license became active on June 14, 2001 **(deprecated)**.

Since the OGC license page said that the OGC software license is now deprecated, should OGC relicenses GeoAPI under Apache 2?

**Comment by ogcscotts** [comment]
@desruisseaux Yes, we request that all software be released under Apache 2.0.

**Comment by desruisseaux** [comment]
URL to OGC software license page seems to have changed. The URL now seems to be:

https://www.ogc.org/about/policies/software-licenses/

But the "Apache Software License 2.0" link on that page is broken.

**Comment by desruisseaux** [comment]
One more question: while most of GeoAPI would be under Apache license, in my understanding the `src/main/metanorma` directory would be an exception. That directory would need to be under the OGC document license:

https://www.ogc.org/about/policies/document-notice/

Is that right? If yes, do we have a text version of above page suitable for inclusion as a `LICENSE` file in the Metanorma source code directory?
